### ISSUE TITLE
latest commit removes all files

### ISSUE THREAD

**Issue by jab** [minrk/homebrew-python-frameworks#1]
The latest commit, 22687148a67c0b81dc5ff8a47048a2a4c54fa4f4, removes all files from the tree. So now, `brew tap minrk/homebrew-python-frameworks && brew cask install python-framework-XY` fails with "No Cask with this name exists". Was this an accident?

Thanks for maintaining homebrew-python-frameworks, it's been serving my open source project's Mac CI well.

**Comment by minrk** [comment]
Whoops! Thanks for noticing. Not sure how I did that. Fixed now.

**Comment by minrk** [comment]
btw, I didn't realize anyone other than me used this!

**Comment by jab** [comment]
Thanks for fixing! I found out about this repo long ago from some other open source project that was using it (can’t remember which), so you just might have a bunch more users. :)
